### PR TITLE
Show download progress on Windows taskbar

### PR DESCRIPTION
**Pull request by counter185**

### CODE REVIEW

**Comment by ScottMichaud** [comment]
Thanks for being our first contributor! I'm currently far behind on a non-Yandere Simulator project so I might take a little time to review this, but I want to let you know that I saw it.

**Comment by counter185** [comment]
It's just an 8 line change, there's not that much to review, but you should check anyway if I put the taskbar specific stuff in the correct lines

**Comment by ScottMichaud** [comment]
Oh yeah that should be quick. I'm talking about putting it into a release.

**Review by ScottMichaud — APPROVED** [review]
Thanks for the contribution! It works great.

**Pull request merged**
